name: Node.js Continuous Integration

on:
  push:

jobs:
  node-test:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Pushed Code on branch
        uses: actions/checkout@v4

      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Check if node_modules cache（after setup-node)
        id: modules-cache
        uses: actions/cache@v4
        with:
          path: ./node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('package-lock.json') }}

      - name: Install node_modules
        if: steps.modules-cache.outputs.cache-hit != 'true'
        shell: bash
        run: npm ci

      - name: TypeScript Test
        run: npm run ts:test

      - name: Next Build
        run: npm run build
